import type { CSSProperties } from "react";

export const s = {
  overlay: {
    position: "fixed",
    inset: 0,
    background: "rgba(0,0,0,0.45)",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    zIndex: 100,
  } as CSSProperties,
  drawer: {
    background: "var(--bg-surface)",
    border: "1px solid var(--border)",
    borderRadius: 12,
    width: 560,
    maxHeight: "80vh",
    overflow: "auto",
    padding: 24,
  } satisfies CSSProperties,
  title: { fontSize: 18, fontWeight: 700, marginBottom: 4 } satisfies CSSProperties,
  subtitle: { fontSize: 13, color: "var(--text-secondary)", marginBottom: 20 } satisfies CSSProperties,
  formGroup: { marginBottom: 16 } satisfies CSSProperties,
  label: { fontSize: 12, fontWeight: 600, color: "var(--text-secondary)", marginBottom: 4, display: "block" } as CSSProperties,
  hint: { fontSize: 12, color: "var(--text-muted)", marginTop: 2 } satisfies CSSProperties,
  input: {
    width: "100%",
    fontSize: 13,
    padding: "7px 10px",
    borderRadius: 6,
    border: "1px solid var(--border)",
    background: "var(--bg-surface)",
    color: "var(--text-primary)",
    outline: "none",
  } satisfies CSSProperties,
  textarea: {
    width: "100%",
    fontSize: 13,
    padding: "7px 10px",
    borderRadius: 6,
    border: "1px solid var(--border)",
    background: "var(--bg-surface)",
    color: "var(--text-primary)",
    outline: "none",
    minHeight: 200,
    fontFamily: "monospace",
    resize: "vertical",
  } as CSSProperties,
  trustBanner: {
    padding: "10px 14px",
    borderRadius: 8,
    background: "rgba(245,158,11,0.12)",
    border: "1px solid rgba(245,158,11,0.3)",
    color: "var(--text-primary)",
    fontSize: 13,
    marginBottom: 16,
    lineHeight: 1.5,
  } satisfies CSSProperties,
  footer: { display: "flex", justifyContent: "flex-end", gap: 10, marginTop: 20 } satisfies CSSProperties,
} as const;
