import type { CSSProperties } from "react";

export const s = {
  card: {
    border: "1px solid var(--border)",
    borderRadius: 8,
    background: "var(--bg-elevated)",
    padding: "16px 18px",
    display: "flex",
    flexDirection: "column",
    gap: 14,
    position: "relative",
  } satisfies CSSProperties,
  header: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  } satisfies CSSProperties,
  headerLeft: {
    display: "flex",
    alignItems: "center",
    gap: 8,
  } satisfies CSSProperties,
  title: {
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: "0.08em",
    textTransform: "uppercase" as const,
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  riskBadge: (color: string, bg: string): CSSProperties => ({
    display: "inline-flex",
    alignItems: "center",
    gap: 4,
    padding: "2px 8px",
    borderRadius: 4,
    fontSize: 10,
    fontWeight: 700,
    letterSpacing: "0.06em",
    color,
    background: bg,
    border: `1px solid ${color}33`,
  }),
  outdatedBadge: {
    display: "inline-flex",
    alignItems: "center",
    padding: "2px 8px",
    borderRadius: 4,
    fontSize: 10,
    fontWeight: 700,
    color: "#fbbf24",
    background: "rgba(251,191,36,0.12)",
    border: "1px solid rgba(251,191,36,0.3)",
  } satisfies CSSProperties,
  sectionLabel: {
    fontSize: 11,
    fontWeight: 600,
    color: "var(--text-muted)",
    textTransform: "uppercase" as const,
    letterSpacing: "0.06em",
    marginBottom: 4,
  } satisfies CSSProperties,
  bodyText: {
    fontSize: 13,
    color: "var(--text-primary)",
    lineHeight: 1.55,
    margin: 0,
  } satisfies CSSProperties,
  riskList: {
    display: "flex",
    flexDirection: "column",
    gap: 8,
  } satisfies CSSProperties,
  riskItem: {
    padding: "8px 10px",
    borderRadius: 6,
    background: "var(--bg-hover)",
    display: "flex",
    flexDirection: "column",
    gap: 4,
  } satisfies CSSProperties,
  riskTitle: {
    fontSize: 12,
    fontWeight: 600,
    color: "var(--text-primary)",
  } satisfies CSSProperties,
  riskDesc: {
    fontSize: 12,
    color: "var(--text-secondary)",
    lineHeight: 1.5,
    margin: 0,
  } satisfies CSSProperties,
  fileLink: {
    display: "inline-flex",
    alignItems: "center",
    gap: 3,
    fontSize: 11,
    color: "var(--accent)",
    fontFamily: "var(--font-mono, monospace)",
    background: "none",
    border: "none",
    padding: "1px 4px",
    borderRadius: 3,
    cursor: "pointer",
    textDecoration: "none",
  } satisfies CSSProperties,
  fileLinksRow: {
    display: "flex",
    flexWrap: "wrap" as const,
    gap: 4,
    marginTop: 2,
  } satisfies CSSProperties,
  reviewFocusList: {
    display: "flex",
    flexDirection: "column",
    gap: 6,
  } satisfies CSSProperties,
  reviewFocusItem: {
    display: "flex",
    alignItems: "flex-start",
    gap: 8,
    fontSize: 12,
  } satisfies CSSProperties,
  focusIndex: {
    minWidth: 20,
    fontWeight: 700,
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  focusNote: {
    color: "var(--text-secondary)",
    lineHeight: 1.4,
    margin: 0,
  } satisfies CSSProperties,
  divider: {
    height: 1,
    background: "var(--border)",
    margin: "4px 0",
  } satisfies CSSProperties,
  findingsSummary: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    padding: "8px 10px",
    borderRadius: 6,
    background: "var(--bg-hover)",
    fontSize: 12,
  } satisfies CSSProperties,
  blockersCount: (hasBlockers: boolean): CSSProperties => ({
    fontWeight: 700,
    color: hasBlockers ? "#f87171" : "var(--text-muted)",
  }),
  findingsCount: {
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  emptyState: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    gap: 12,
    padding: "32px 0",
    color: "var(--text-muted)",
    fontSize: 13,
  } satisfies CSSProperties,
  generateBtn: {
    padding: "6px 14px",
    borderRadius: 6,
    fontSize: 12,
    fontWeight: 600,
    cursor: "pointer",
    border: "1px solid var(--border)",
    background: "var(--bg-elevated)",
    color: "var(--text-primary)",
  } satisfies CSSProperties,
  regenerateBtn: {
    padding: "4px 10px",
    borderRadius: 5,
    fontSize: 11,
    fontWeight: 600,
    cursor: "pointer",
    border: "1px solid var(--border)",
    background: "transparent",
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  /** Overlay container for regeneration state — shows spinner over existing brief. */
  overlay: {
    position: "absolute",
    inset: 0,
    borderRadius: 8,
    background: "rgba(0,0,0,0.35)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 10,
  } satisfies CSSProperties,
  skeletonRow: {
    height: 12,
    borderRadius: 4,
    background: "var(--bg-hover)",
    animation: "pulse 1.5s ease-in-out infinite",
  } satisfies CSSProperties,
} as const;
