import type { CSSProperties } from "react";

export const s = {
  overlay: {
    position: "fixed",
    inset: 0,
    background: "rgba(0,0,0,0.45)",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    zIndex: 100,
  } as CSSProperties,
  drawer: {
    background: "var(--bg-surface)",
    border: "1px solid var(--border)",
    borderRadius: 12,
    width: 520,
    maxHeight: "85vh",
    overflow: "auto",
    padding: 24,
  } satisfies CSSProperties,
  title: { fontSize: 18, fontWeight: 700, marginBottom: 4 } satisfies CSSProperties,
  subtitle: { fontSize: 13, color: "var(--text-secondary)", marginBottom: 16 } satisfies CSSProperties,
  searchWrap: { marginBottom: 12 } satisfies CSSProperties,
  searchInput: {
    width: "100%",
    fontSize: 13,
    padding: "8px 12px",
    borderRadius: 6,
    border: "1px solid var(--border)",
    background: "var(--bg-surface)",
    color: "var(--text-primary)",
    outline: "none",
  } satisfies CSSProperties,
  chipRow: {
    display: "flex",
    gap: 8,
    flexWrap: "wrap",
    marginBottom: 16,
  } as CSSProperties,
  chip: (active: boolean): CSSProperties => ({
    fontSize: 12,
    fontWeight: 500,
    padding: "4px 12px",
    borderRadius: 14,
    border: active ? "1px solid var(--accent)" : "1px solid var(--border)",
    background: active ? "var(--accent-bg)" : "transparent",
    color: active ? "var(--accent)" : "var(--text-secondary)",
    cursor: "pointer",
  }),
  resultsList: {
    display: "flex",
    flexDirection: "column",
    gap: 10,
  } as CSSProperties,
  resultCard: {
    border: "1px solid var(--border)",
    borderRadius: 8,
    padding: "14px 16px",
  } satisfies CSSProperties,
  resultHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 4,
  } satisfies CSSProperties,
  resultName: { fontSize: 14, fontWeight: 700 } satisfies CSSProperties,
  resultStars: {
    fontSize: 12,
    fontWeight: 600,
    color: "#f59e0b",
  } satisfies CSSProperties,
  resultDesc: {
    fontSize: 13,
    color: "var(--text-secondary)",
    marginBottom: 10,
  } satisfies CSSProperties,
  resultFooter: {
    display: "flex",
    alignItems: "center",
    gap: 8,
  } satisfies CSSProperties,
  resultRepo: {
    fontSize: 12,
    color: "var(--text-muted)",
    fontFamily: "monospace",
  } satisfies CSSProperties,
  resultLang: {
    fontSize: 11,
    fontWeight: 600,
    padding: "2px 8px",
    borderRadius: 4,
    background: "var(--bg-hover)",
    color: "var(--text-secondary)",
  } satisfies CSSProperties,
} as const;
